// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebAPI.Models;

namespace MyWebAPI.Migrations
{
    [DbContext(typeof(TodoContext))]
    partial class TodoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyWebAPI.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "123456",
                            Username = "user01"
                        },
                        new
                        {
                            Id = 2,
                            Password = "123456",
                            Username = "user02"
                        },
                        new
                        {
                            Id = 3,
                            Password = "123456",
                            Username = "user03"
                        },
                        new
                        {
                            Id = 4,
                            Password = "123456",
                            Username = "user04"
                        },
                        new
                        {
                            Id = 5,
                            Password = "123456",
                            Username = "user05"
                        });
                });

            modelBuilder.Entity("MyWebAPI.Models.AccountCourse", b =>
                {
                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountCourse");

                    b.HasData(
                        new
                        {
                            CourseId = "KH02",
                            AccountId = 1
                        },
                        new
                        {
                            CourseId = "KH01",
                            AccountId = 3
                        },
                        new
                        {
                            CourseId = "KH04",
                            AccountId = 2
                        },
                        new
                        {
                            CourseId = "KH03",
                            AccountId = 3
                        });
                });

            modelBuilder.Entity("MyWebAPI.Models.Course", b =>
                {
                    b.Property<string>("MaKhoaHoc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Dongia")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhoaHoc");

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            MaKhoaHoc = "KH01",
                            DiaChi = "Quang Binh",
                            Dongia = 200000,
                            TenKhoaHoc = "ASP.NET"
                        },
                        new
                        {
                            MaKhoaHoc = "KH02",
                            DiaChi = "Da Nang",
                            Dongia = 300000,
                            TenKhoaHoc = "Java Spring"
                        },
                        new
                        {
                            MaKhoaHoc = "KH03",
                            DiaChi = "Da Nang",
                            Dongia = 400000,
                            TenKhoaHoc = "C++"
                        },
                        new
                        {
                            MaKhoaHoc = "KH04",
                            DiaChi = "Quang Binh",
                            Dongia = 500000,
                            TenKhoaHoc = "HTML"
                        });
                });

            modelBuilder.Entity("MyWebAPI.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = 1,
                            Age = 22,
                            Fullname = "Bui van Hoa",
                            IdNo = "1233453421321"
                        },
                        new
                        {
                            Id = 2,
                            AccountId = 2,
                            Age = 12,
                            Fullname = "Nguyen Van A",
                            IdNo = "12343534521321"
                        },
                        new
                        {
                            Id = 3,
                            AccountId = 3,
                            Age = 42,
                            Fullname = "Tran Van B",
                            IdNo = "1321435"
                        },
                        new
                        {
                            Id = 4,
                            AccountId = 4,
                            Age = 22,
                            Fullname = "Nguyen Thi C",
                            IdNo = "12325345341321"
                        },
                        new
                        {
                            Id = 5,
                            AccountId = 5,
                            Age = 42,
                            Fullname = "XXXX YYY ZZZZ",
                            IdNo = "12334534521321"
                        });
                });

            modelBuilder.Entity("MyWebAPI.Models.TodoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("MyWebAPI.Models.AccountCourse", b =>
                {
                    b.HasOne("MyWebAPI.Models.Account", "Account")
                        .WithMany("AccountCourses")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyWebAPI.Models.Course", "Course")
                        .WithMany("AccountCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("MyWebAPI.Models.Profile", b =>
                {
                    b.HasOne("MyWebAPI.Models.Account", "Account")
                        .WithOne("Profile")
                        .HasForeignKey("MyWebAPI.Models.Profile", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("MyWebAPI.Models.Account", b =>
                {
                    b.Navigation("AccountCourses");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("MyWebAPI.Models.Course", b =>
                {
                    b.Navigation("AccountCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
